# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3378fe70837a38e3453ea015d3614a71"
name = "premium-extension-app"
handle = "premium-extension-app"
application_url = "https://beta-undefined-keen-trademark.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c0df92f9.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://beta-undefined-keen-trademark.trycloudflare.com/auth/callback",
  "https://beta-undefined-keen-trademark.trycloudflare.com/auth/shopify/callback",
  "https://beta-undefined-keen-trademark.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
